export const themes = {
    'default-light': {
        id: 'default-light',
        name: 'Default Light',
        type: 'light',
        colors: {
            primary: '#1976d2',
            secondary: '#7b1fa2',
            background: '#f5f5f5',
            surface: '#ffffff',
            text: '#333333',
            border: '#cccccc',
            accent: '#ff4081',
            success: '#4caf50',
            warning: '#ff9800',
            error: '#f44336',
        },
        nodeStyles: {
            object: {
                backgroundColor: '#e3f2fd',
                borderColor: '#1976d2',
                borderWidth: 2,
                borderRadius: 25,
                color: '#333333',
                fontSize: 14,
                fontFamily: 'Arial, sans-serif',
                padding: 12,
                margin: 8,
                shadow: '0 2px 8px rgba(0,0,0,0.1)',
                opacity: 1,
            },
            array: {
                backgroundColor: '#f3e5f5',
                borderColor: '#7b1fa2',
                borderWidth: 2,
                borderRadius: 15,
                color: '#333333',
                fontSize: 14,
                fontFamily: 'Arial, sans-serif',
                padding: 12,
                margin: 8,
                shadow: '0 2px 8px rgba(0,0,0,0.1)',
                opacity: 1,
            },
            string: {
                backgroundColor: '#e8f5e8',
                borderColor: '#388e3c',
                borderWidth: 2,
                borderRadius: 20,
                color: '#333333',
                fontSize: 14,
                fontFamily: 'Arial, sans-serif',
                padding: 12,
                margin: 8,
                shadow: '0 2px 8px rgba(0,0,0,0.1)',
                opacity: 1,
            },
            number: {
                backgroundColor: '#fff3e0',
                borderColor: '#f57c00',
                borderWidth: 2,
                borderRadius: 20,
                color: '#333333',
                fontSize: 14,
                fontFamily: 'Arial, sans-serif',
                padding: 12,
                margin: 8,
                shadow: '0 2px 8px rgba(0,0,0,0.1)',
                opacity: 1,
            },
            boolean: {
                backgroundColor: '#fce4ec',
                borderColor: '#c2185b',
                borderWidth: 2,
                borderRadius: 20,
                color: '#333333',
                fontSize: 14,
                fontFamily: 'Arial, sans-serif',
                padding: 12,
                margin: 8,
                shadow: '0 2px 8px rgba(0,0,0,0.1)',
                opacity: 1,
            },
            null: {
                backgroundColor: '#f5f5f5',
                borderColor: '#757575',
                borderWidth: 2,
                borderRadius: 20,
                color: '#999999',
                fontSize: 14,
                fontFamily: 'Arial, sans-serif',
                padding: 12,
                margin: 8,
                shadow: '0 2px 8px rgba(0,0,0,0.1)',
                opacity: 1,
            },
        },
        connectionStyle: {
            stroke: '#666666',
            strokeWidth: 2,
            opacity: 0.8,
        },
        fonts: {
            primary: 'Arial, sans-serif',
            monospace: 'Consolas, Monaco, monospace',
        },
    },
    'default-dark': {
        id: 'default-dark',
        name: 'Default Dark',
        type: 'dark',
        colors: {
            primary: '#64b5f6',
            secondary: '#ba68c8',
            background: '#121212',
            surface: '#1e1e1e',
            text: '#ffffff',
            border: '#444444',
            accent: '#ff4081',
            success: '#66bb6a',
            warning: '#ffb74d',
            error: '#ef5350',
        },
        nodeStyles: {
            object: {
                backgroundColor: '#1e3a8a',
                borderColor: '#64b5f6',
                borderWidth: 2,
                borderRadius: 25,
                color: '#ffffff',
                fontSize: 14,
                fontFamily: 'Arial, sans-serif',
                padding: 12,
                margin: 8,
                shadow: '0 2px 8px rgba(0,0,0,0.3)',
                opacity: 1,
            },
            array: {
                backgroundColor: '#4a148c',
                borderColor: '#ba68c8',
                borderWidth: 2,
                borderRadius: 15,
                color: '#ffffff',
                fontSize: 14,
                fontFamily: 'Arial, sans-serif',
                padding: 12,
                margin: 8,
                shadow: '0 2px 8px rgba(0,0,0,0.3)',
                opacity: 1,
            },
            string: {
                backgroundColor: '#1b5e20',
                borderColor: '#66bb6a',
                borderWidth: 2,
                borderRadius: 20,
                color: '#ffffff',
                fontSize: 14,
                fontFamily: 'Arial, sans-serif',
                padding: 12,
                margin: 8,
                shadow: '0 2px 8px rgba(0,0,0,0.3)',
                opacity: 1,
            },
            number: {
                backgroundColor: '#e65100',
                borderColor: '#ffb74d',
                borderWidth: 2,
                borderRadius: 20,
                color: '#ffffff',
                fontSize: 14,
                fontFamily: 'Arial, sans-serif',
                padding: 12,
                margin: 8,
                shadow: '0 2px 8px rgba(0,0,0,0.3)',
                opacity: 1,
            },
            boolean: {
                backgroundColor: '#880e4f',
                borderColor: '#f06292',
                borderWidth: 2,
                borderRadius: 20,
                color: '#ffffff',
                fontSize: 14,
                fontFamily: 'Arial, sans-serif',
                padding: 12,
                margin: 8,
                shadow: '0 2px 8px rgba(0,0,0,0.3)',
                opacity: 1,
            },
            null: {
                backgroundColor: '#263238',
                borderColor: '#78909c',
                borderWidth: 2,
                borderRadius: 20,
                color: '#b0bec5',
                fontSize: 14,
                fontFamily: 'Arial, sans-serif',
                padding: 12,
                margin: 8,
                shadow: '0 2px 8px rgba(0,0,0,0.3)',
                opacity: 1,
            },
        },
        connectionStyle: {
            stroke: '#999999',
            strokeWidth: 2,
            opacity: 0.8,
        },
        fonts: {
            primary: 'Arial, sans-serif',
            monospace: 'Consolas, Monaco, monospace',
        },
    },
    'glassmorphic-light': {
        id: 'glassmorphic-light',
        name: 'Glassmorphic Light',
        type: 'glassmorphic',
        colors: {
            primary: 'rgba(255, 255, 255, 0.3)',
            secondary: 'rgba(255, 255, 255, 0.2)',
            background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
            surface: 'rgba(255, 255, 255, 0.1)',
            text: '#ffffff',
            border: 'rgba(255, 255, 255, 0.3)',
            accent: '#ff6b6b',
            success: '#51cf66',
            warning: '#ffd93d',
            error: '#ff6b6b',
        },
        nodeStyles: {
            object: {
                backgroundColor: 'rgba(255, 255, 255, 0.15)',
                borderColor: 'rgba(255, 255, 255, 0.3)',
                borderWidth: 2,
                borderRadius: 25,
                color: '#ffffff',
                fontSize: 14,
                fontFamily: 'Arial, sans-serif',
                padding: 12,
                margin: 8,
                shadow: '0 8px 32px rgba(0, 0, 0, 0.1)',
                opacity: 0.8,
            },
            array: {
                backgroundColor: 'rgba(255, 255, 255, 0.1)',
                borderColor: 'rgba(255, 255, 255, 0.25)',
                borderWidth: 2,
                borderRadius: 15,
                color: '#ffffff',
                fontSize: 14,
                fontFamily: 'Arial, sans-serif',
                padding: 12,
                margin: 8,
                shadow: '0 8px 32px rgba(0, 0, 0, 0.1)',
                opacity: 0.8,
            },
            string: {
                backgroundColor: 'rgba(255, 255, 255, 0.12)',
                borderColor: 'rgba(255, 255, 255, 0.28)',
                borderWidth: 2,
                borderRadius: 20,
                color: '#ffffff',
                fontSize: 14,
                fontFamily: 'Arial, sans-serif',
                padding: 12,
                margin: 8,
                shadow: '0 8px 32px rgba(0, 0, 0, 0.1)',
                opacity: 0.8,
            },
            number: {
                backgroundColor: 'rgba(255, 255, 255, 0.18)',
                borderColor: 'rgba(255, 255, 255, 0.32)',
                borderWidth: 2,
                borderRadius: 20,
                color: '#ffffff',
                fontSize: 14,
                fontFamily: 'Arial, sans-serif',
                padding: 12,
                margin: 8,
                shadow: '0 8px 32px rgba(0, 0, 0, 0.1)',
                opacity: 0.8,
            },
            boolean: {
                backgroundColor: 'rgba(255, 255, 255, 0.14)',
                borderColor: 'rgba(255, 255, 255, 0.3)',
                borderWidth: 2,
                borderRadius: 20,
                color: '#ffffff',
                fontSize: 14,
                fontFamily: 'Arial, sans-serif',
                padding: 12,
                margin: 8,
                shadow: '0 8px 32px rgba(0, 0, 0, 0.1)',
                opacity: 0.8,
            },
            null: {
                backgroundColor: 'rgba(255, 255, 255, 0.08)',
                borderColor: 'rgba(255, 255, 255, 0.2)',
                borderWidth: 2,
                borderRadius: 20,
                color: 'rgba(255, 255, 255, 0.7)',
                fontSize: 14,
                fontFamily: 'Arial, sans-serif',
                padding: 12,
                margin: 8,
                shadow: '0 8px 32px rgba(0, 0, 0, 0.1)',
                opacity: 0.8,
            },
        },
        connectionStyle: {
            stroke: 'rgba(255, 255, 255, 0.4)',
            strokeWidth: 2,
            opacity: 0.6,
        },
        fonts: {
            primary: 'Arial, sans-serif',
            monospace: 'Consolas, Monaco, monospace',
        },
    },
    'retro-terminal': {
        id: 'retro-terminal',
        name: 'Retro Terminal',
        type: 'retro',
        colors: {
            primary: '#00ff00',
            secondary: '#00ffff',
            background: '#000000',
            surface: '#1a1a1a',
            text: '#00ff00',
            border: '#00ff00',
            accent: '#ff00ff',
            success: '#00ff00',
            warning: '#ffff00',
            error: '#ff0000',
        },
        nodeStyles: {
            object: {
                backgroundColor: '#0a0a0a',
                borderColor: '#00ff00',
                borderWidth: 2,
                borderRadius: 0,
                color: '#00ff00',
                fontSize: 12,
                fontFamily: 'Courier New, monospace',
                padding: 8,
                margin: 4,
                shadow: 'none',
                opacity: 1,
            },
            array: {
                backgroundColor: '#0f0f0f',
                borderColor: '#00ffff',
                borderWidth: 2,
                borderRadius: 0,
                color: '#00ffff',
                fontSize: 12,
                fontFamily: 'Courier New, monospace',
                padding: 8,
                margin: 4,
                shadow: 'none',
                opacity: 1,
            },
            string: {
                backgroundColor: '#050505',
                borderColor: '#ffff00',
                borderWidth: 2,
                borderRadius: 0,
                color: '#ffff00',
                fontSize: 12,
                fontFamily: 'Courier New, monospace',
                padding: 8,
                margin: 4,
                shadow: 'none',
                opacity: 1,
            },
            number: {
                backgroundColor: '#0a0a0a',
                borderColor: '#ff00ff',
                borderWidth: 2,
                borderRadius: 0,
                color: '#ff00ff',
                fontSize: 12,
                fontFamily: 'Courier New, monospace',
                padding: 8,
                margin: 4,
                shadow: 'none',
                opacity: 1,
            },
            boolean: {
                backgroundColor: '#050505',
                borderColor: '#ff6600',
                borderWidth: 2,
                borderRadius: 0,
                color: '#ff6600',
                fontSize: 12,
                fontFamily: 'Courier New, monospace',
                padding: 8,
                margin: 4,
                shadow: 'none',
                opacity: 1,
            },
            null: {
                backgroundColor: '#000000',
                borderColor: '#666666',
                borderWidth: 2,
                borderRadius: 0,
                color: '#666666',
                fontSize: 12,
                fontFamily: 'Courier New, monospace',
                padding: 8,
                margin: 4,
                shadow: 'none',
                opacity: 1,
            },
        },
        connectionStyle: {
            stroke: '#00ff00',
            strokeWidth: 1,
            strokeDasharray: '5,5',
            opacity: 0.7,
        },
        fonts: {
            primary: 'Courier New, monospace',
            monospace: 'Courier New, monospace',
        },
    },
    'brutalist': {
        id: 'brutalist',
        name: 'Brutalist',
        type: 'brutalist',
        colors: {
            primary: '#000000',
            secondary: '#ff0000',
            background: '#ffffff',
            surface: '#ffffff',
            text: '#000000',
            border: '#000000',
            accent: '#ff0000',
            success: '#000000',
            warning: '#000000',
            error: '#ff0000',
        },
        nodeStyles: {
            object: {
                backgroundColor: '#ffffff',
                borderColor: '#000000',
                borderWidth: 4,
                borderRadius: 0,
                color: '#000000',
                fontSize: 16,
                fontFamily: 'Arial Black, sans-serif',
                padding: 16,
                margin: 8,
                shadow: '8px 8px 0px #000000',
                opacity: 1,
            },
            array: {
                backgroundColor: '#ffffff',
                borderColor: '#000000',
                borderWidth: 4,
                borderRadius: 0,
                color: '#000000',
                fontSize: 16,
                fontFamily: 'Arial Black, sans-serif',
                padding: 16,
                margin: 8,
                shadow: '8px 8px 0px #000000',
                opacity: 1,
            },
            string: {
                backgroundColor: '#ffffff',
                borderColor: '#000000',
                borderWidth: 4,
                borderRadius: 0,
                color: '#000000',
                fontSize: 16,
                fontFamily: 'Arial Black, sans-serif',
                padding: 16,
                margin: 8,
                shadow: '8px 8px 0px #000000',
                opacity: 1,
            },
            number: {
                backgroundColor: '#ffffff',
                borderColor: '#000000',
                borderWidth: 4,
                borderRadius: 0,
                color: '#000000',
                fontSize: 16,
                fontFamily: 'Arial Black, sans-serif',
                padding: 16,
                margin: 8,
                shadow: '8px 8px 0px #000000',
                opacity: 1,
            },
            boolean: {
                backgroundColor: '#ffffff',
                borderColor: '#000000',
                borderWidth: 4,
                borderRadius: 0,
                color: '#000000',
                fontSize: 16,
                fontFamily: 'Arial Black, sans-serif',
                padding: 16,
                margin: 8,
                shadow: '8px 8px 0px #000000',
                opacity: 1,
            },
            null: {
                backgroundColor: '#ffffff',
                borderColor: '#666666',
                borderWidth: 4,
                borderRadius: 0,
                color: '#666666',
                fontSize: 16,
                fontFamily: 'Arial Black, sans-serif',
                padding: 16,
                margin: 8,
                shadow: '8px 8px 0px #000000',
                opacity: 1,
            },
        },
        connectionStyle: {
            stroke: '#000000',
            strokeWidth: 4,
            opacity: 1,
        },
        fonts: {
            primary: 'Arial Black, sans-serif',
            monospace: 'Courier New, monospace',
        },
    },
};
export const getTheme = (themeId) => {
    return themes[themeId] || themes['default-light'];
};
export const getAllThemes = () => {
    return Object.values(themes);
};
export const getThemeIds = () => {
    return Object.keys(themes);
};
